# Generated by Django 5.2.6 on 2025-09-30 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_salary_alter_job_company_alter_job_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-posted_at"],
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level"),
                    ("junior", "Junior"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                ],
                default="entry",
                help_text="Required experience level for this position",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Uncheck to deactivate this job posting"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full Time"),
                    ("part-time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("temporary", "Temporary"),
                    ("remote", "Remote"),
                ],
                default="full-time",
                help_text="Select the type of employment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="remote_allowed",
            field=models.BooleanField(
                default=False, help_text="Check if remote work is allowed"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time when the job was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(
                help_text="Enter the company name (2-150 characters)",
                max_length=150,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Company name must be at least 2 characters long."
                    ),
                    django.core.validators.RegexValidator(
                        message="Company name can only contain letters, numbers, spaces, and basic punctuation.",
                        regex="^[a-zA-Z0-9\\s\\-\\.\\&\\,\\(\\)]+$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                help_text="Provide a detailed job description (minimum 50 characters)",
                validators=[
                    django.core.validators.MinLengthValidator(
                        50,
                        message="Job description must be at least 50 characters long.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(
                help_text="Enter job location (city, state/country)",
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Location must be at least 2 characters long."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time when the job was posted"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual salary (optional)",
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="Salary must be greater than 0."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                help_text="Enter a descriptive job title (5-200 characters)",
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="Job title must be at least 5 characters long."
                    ),
                    django.core.validators.RegexValidator(
                        message="Job title can only contain letters, numbers, spaces, and basic punctuation.",
                        regex="^[a-zA-Z0-9\\s\\-\\+\\#\\(\\)\\/]+$",
                    ),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["company"], name="jobs_job_company_73ae7f_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location"], name="jobs_job_locatio_8b2f8c_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["job_type"], name="jobs_job_job_typ_f6c220_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["experience_level"], name="jobs_job_experie_09027f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active"], name="jobs_job_is_acti_b6ae73_idx"
            ),
        ),
    ]
